apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: http-server
nacci
  labels:
    app: http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
        lang: go
    spec:
      containers:
        - name: http-server
          image: python:alpine
          command: ["python", "-m", "http.server", "8000"] 
          ports:
            - containerPort: 8000
