apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  selector:
    app: http-server
    status: active
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
