global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: fibonacci
    static_configs:
      - targets:
        - fibonacci.default.svc.cluster.local
