apiVersion: apps/v1
kind: Deployment
metadata:
  name: memleak
spec:
  selector:
    matchLabels:
      app: memleak
  template:
    metadata:
      labels:
        app: memleak
    spec:
      containers:
        - name: memleak
          image: palnabarun/memleak
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
